### ISSUE TITLE
Order types and weight map

### ISSUE THREAD

**Issue by coungard** [coungard/delivery-club#21]
На данный момент при создании заказа указываются тип посылки и вес. Необходимо доработать логику так, чтобы тип посылки автоматически указывался от его веса. 
Добавить новый рест _**/parcel/types**_

![изображение](https://github.com/coungard/delivery-club/assets/32792990/747efa61-e293-453b-bc43-d9073db6840f)

Например, задать пропорции:
от 0 до 3 кг - SMALL
от 3 до 15 кг - MEDIUM
от 15 до 50 кг - LARGE
от 50 и выше - EXTRA_LARGE

**Comment by Konstantin-Pavlov** [comment]
Add db table weights and the necessary services to get this data in the "/weight-map" endpoint.
http://localhost:8082/order/weight-map
![image](https://github.com/user-attachments/assets/19f2b38d-073e-4594-b3c5-171e684ba0d6)

**Comment by Konstantin-Pavlov** [comment]
done
